export const FIND_PRODUCT = "FIND_PRODUCT"
export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_PRODUCTS_BY_CATEGORY= "GET_PRODUCTS_BY_CATEGORY"

export const GET_WISHLIST_PRODUCTS ="GET_WISHLIST_PRODUCTS"
export const GET_Total_PRICE ="GET_Total_PRICE"
export const ORDER_STATUS ="ORDER_STATUS"
